
import { jsPDF } from 'jspdf';

export const exportToTXT = (filename: string, content: string) => {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.txt`;
  link.click();
  URL.revokeObjectURL(url);
};

export const exportToCSV = (filename: string, content: string) => {
  // Convert text content into a simple CSV format
  // We split by lines and escape quotes for basic spreadsheet compatibility
  const rows = content.split('\n').filter(line => line.trim() !== '');
  const csvContent = rows.map(row => `"${row.replace(/"/g, '""')}"`).join('\n');
  
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.csv`;
  link.click();
  URL.revokeObjectURL(url);
};

export const exportToPDF = (filename: string, content: string, title?: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxLineWidth = pageWidth - margin * 2;
  let cursorY = 20;

  // Professional Styling: Header
  if (title) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.text(title.toUpperCase(), margin, cursorY);
    cursorY += 10;
    doc.setLineWidth(0.5);
    doc.line(margin, cursorY, pageWidth - margin, cursorY);
    cursorY += 15;
  }

  // Content Styling
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(40, 40, 40);

  const lines = doc.splitTextToSize(content, maxLineWidth);
  
  lines.forEach((line: string) => {
    if (cursorY > pageHeight - margin) {
      doc.addPage();
      cursorY = 20;
    }
    doc.text(line, margin, cursorY);
    cursorY += 7; // Line height
  });

  // Footer: Branding
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by SKLearn AI Hub - Page ${i} of ${totalPages}`, margin, pageHeight - 10);
  }

  doc.save(`${filename}.pdf`);
};

export const exportToHTML = (filename: string, content: string) => {
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${filename}</title>
      <style>
        body { font-family: 'Inter', sans-serif; padding: 60px; line-height: 1.8; max-width: 800px; margin: auto; color: #333; }
        h1 { font-family: 'Playfair Display', serif; border-bottom: 2px solid #eee; padding-bottom: 20px; margin-bottom: 40px; }
        pre { white-space: pre-wrap; word-wrap: break-word; font-family: inherit; font-size: 16px; }
        .footer { margin-top: 60px; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 20px; }
      </style>
    </head>
    <body>
      <h1>${filename.replace(/_/g, ' ')}</h1>
      <pre>${content}</pre>
      <div class="footer">Generated by SKLearn AI Hub</div>
    </body>
    </html>
  `;
  const blob = new Blob([htmlContent], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.html`;
  link.click();
  URL.revokeObjectURL(url);
};
